# Base image
FROM python:3.11-slim

# Set workdir
WORKDIR /app

# Copy files
COPY requirements_ingestion.txt .
RUN pip install --no-cache-dir -r requirements_ingestion.txt

COPY /ingestion app/ingestion
COPY /common app/common

# Expose port
EXPOSE 8000

# Run FastAPI
CMD ["uvicorn", "ingestion.main:app", "--host", "0.0.0.0", "--port", "8000"]