# -------- Build Stage --------
FROM python:3.11-slim AS builder

# Set workdir
WORKDIR /app

RUN mkdir -p services/ingestion services/common

COPY services/ingestion services/ingestion
COPY services/common services/common

# Install build dependencies only if needed
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_ingestion.txt .

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements_ingestion.txt --target /install

# -------- Runtime Stage --------
FROM python:3.11-slim

# Set workdir
WORKDIR /app

# Copy only installed dependencies
COPY --from=builder /install /usr/local/lib/python3.11/site-packages

COPY --from=builder /app/services /app/services

# Expose port
EXPOSE 8000

# Run FastAPI
CMD ["python", "-m", "uvicorn", "services.ingestion.main:app", "--host", "0.0.0.0", "--port", "8000"]