apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
    spec:
      serviceAccountName: ocr-ksa
      containers:
      - name: ocr
        image: asia-south1-docker.pkg.dev/billsight-ai-project/billsight-repo/ocr:v4
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: app-config-v1